hrcentre/urls.py
from django.urls import path

from . import views

app_name = 'hrcentre'

urlpatterns = [
    path('', views.index, name='index'),
    path('setups/corporation/<int:corp_id>/', views.CorporationAuditListView.as_view(), name='corp_view'),
    path('setups/alliance/<int:alliance_id>/', views.AllianceAuditListView.as_view(), name='alliance_view'),
    path('users/<int:user_id>/', views.user_view, name='user_view'),
    path('users/<int:user_id>/labels/', views.user_labels_view, name='user_labels'),
    path('users/<int:user_id>/notes/', views.user_notes_view, name='user_notes'),
    path('dashboard/labels/', views.dashboard_post, name='dashboard_post'),
]

hrcentre/templates/hrcentre/base.html
{% extends 'allianceauth/base-bs5.html' %}
{% load i18n %}

{% block header_nav_brand %}
    {% translate "HR Centre" %}
{% endblock header_nav_brand %}

{% block page_title %}{% translate "HR Centre" %}{% endblock page_title %}

{% block content %}
    <div class="col-lg-12">
        {% block hrcentre_page_header %}{% endblock hrcentre_page_header %}
        <div class="container-fluid mt-3 px-0">
            {% block hrcentre_content %}{% endblock hrcentre_content %}
        </div>
    </div>
{% endblock content %}

hrcentre/templates/hrcentre/dashboard_labels.html
{% load i18n %}

<div id="hrcentre-labels" class="col-6 mb-3">
    <div class="card px-2">
        <div class="card-body text-center">
            {% translate "HR Centre" as widget_title %}
            {% include "framework/dashboard/widget-title.html" with title=widget_title %}
            <div class="row justify-content-center">
                <div class="col-lg-4">
                    {% url "hrcentre:dashboard_post" as form_action %}
                    {% include "hrcentre/label_form.html" with form=form action=form_action %}
                </div>
            </div>
        </div>
    </div>
</div>

hrcentre/templates/hrcentre/edit_labels.html
{% extends "hrcentre/base.html" %}

{% block hrcentre_page_header %}
    <h1 class="page-header text-center">{{ page_header }}</h1>
{% endblock hrcentre_page_header %}

{% block hrcentre_content %}
    <div class="row">
        <div class="col-12 px-4">
            {% include "hrcentre/label_form.html" with form=form %}
        </div>
    </div>
{% endblock hrcentre_content %}

hrcentre/templates/hrcentre/generic_form.html
{% extends "hrcentre/base.html" %}
{% load i18n %}
{% load django_bootstrap5 %}

{% block hrcentre_page_header %}
    <h1 class="page-header text-center">{{ page_header }}</h1>
{% endblock hrcentre_page_header %}

{% block hrcentre_content %}
    <div class="row">
        <div class="col-12 px-4">
            <form method="post">
                {% csrf_token %}
                {% bootstrap_form form %}
                <button type="submit" class="btn btn-primary mt-3">{% translate "Submit" %}</button>
            </form>
        </div>
    </div>
{% endblock hrcentre_content %}

hrcentre/templates/hrcentre/index.html
{% extends "hrcentre/base.html" %}
{% load i18n %}

{% block hrcentre_page_header %}<h1 class="page-header text-center">HR Centre</h1>{% endblock hrcentre_page_header %}


{% block extra_css %}
    {% include "bundles/datatables-css-bs5.html" %}
{% endblock extra_css %}

{% block hrcentre_content %}
    <div class="row">
        <div class="col-12 px-4">
            <div class="card mt-2">
                <div class="card-header text-center">{% translate "Alliances" %}</div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-aa">
                            <thead>
                                <tr>
                                    <th scope="col">{% translate "Name" %}</th>
                                    <th scope="col"></th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for alliance_setup in alliance_setups %}
                                    <tr>
                                        <td>
                                            <img src="{{ alliance_setup.alliance.logo_url_32 }}" class="rounded me-2">
                                            <span>{{ alliance_setup.alliance.alliance_name }}</span>
                                        </td>
                                        <td><a class="btn btn-info" href="{% url "hrcentre:alliance_view" alliance_setup.pk %}">View</a></td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <div class="card mt-4">
                <div class="card-header text-center">{% translate "Corporations" %}</div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-aa">
                            <thead>
                                <tr>
                                    <th scope="col">{% translate "Name" %}</th>
                                    <th scope="col"></th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for corp_setup in corp_setups %}
                                    <tr>
                                        <td>
                                            <img src="{{ corp_setup.corporation.logo_url_32 }}" class="rounded me-2">
                                            <span>{{ corp_setup.corporation.corporation_name }}</span>
                                        </td>
                                        <td><a class="btn btn-info" href="{% url "hrcentre:corp_view" corp_setup.pk %}">View</a></td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock hrcentre_content %}

{% block extra_javascript %}
    {% include "bundles/datatables-js-bs5.html" %}
{% endblock extra_javascript %}

{% block extra_script %}
    $(document).ready(function() {
        $('.table-aa').DataTable({
            columnDefs: [
                { orderable: false, searchable: false, targets: 1 },
            ]
        });
    });
{% endblock extra_script %}

hrcentre/templates/hrcentre/label_form.html
{% load django_bootstrap5 %}
{% load i18n %}
<form class="was-validated" method="post" action="{{ form_action }}" novalidate>
    {% csrf_token %}

    {% bootstrap_form_errors form type='non_fields' %}

    {% for field in form %}
        <div class="mb-4">
            <legend>{{ field.label }}:</legend>
            {{ field }}
            {% if field.help_text %}
                <p class="form-text mb-1" id="{{ field.auto_id }}_helptext">
                    {{ field.help_text|safe }}
                </p>
            {% endif %}
            {% for error in field.errors %}
                <div class="text-danger">{{ error }}</div>
            {% endfor %}
        </div>
    {% endfor %}
    
    <button type="submit" class="btn btn-primary mt-3">{% translate "Submit" %}</button>
</form>

hrcentre/templates/hrcentre/user_labels.html
{% extends "hrcentre/base.html" %}
{% load i18n %}
{% load django_bootstrap5 %}

{% block hrcentre_page_header %}
    <h1 class="page-header text-center">
        {% blocktranslate with name=main.character.character_name %}
            {{ name }} labels
        {% endblocktranslate %}
    </h1>
{% endblock hrcentre_page_header %}

{% block hrcentre_content %}
    <div class="row">
        <div class="col-12">
            <form method="post">
                {% csrf_token %}
                {% bootstrap_form form %}
                <button type="submit" class="btn btn-primary mt-3">{% translate "Submit" %}</button>
            </form>
        </div>
    </div>
{% endblock hrcentre_content %}

hrcentre/templates/hrcentre/user_view.html
{% extends "hrcentre/base.html" %}
{% load i18n %}
{% load tz %}

{% block hrcentre_page_header %}<h1 class="page-header text-center">{{ main.character.character_name }}</h1>{% endblock hrcentre_page_header %}

{% block hrcentre_content %}
    <div class="row justify-content-center g-4">
        <div class="col-3">
            <div class="card text-center">
                <div class="card-header">{% translate "Character Audit" %}</div>
                <div class="card-body">
                    <a href="{% url "corptools:reactmain" main.character.character_id %}">
                        {% translate "View on Character Audit" %}
                    </a>
                </div>
            </div>
        </div>
        <div class="col-3">
            <div class="card text-center">
                <div class="card-header">{% translate "Number of characters" %}</div>
                <div class="card-body">{{ main.number_of_chars }}</div>
            </div>
        </div>
    </div>
    <div class="row justify-content-center gy-4 mt-2">
        <div class="col-auto">
            <div class="card text-center">
                <div class="card-header">{% translate "User labels" %}</div>
                <div class="card-body">
                    {% for label in labels %}
                        <span class="badge {{ label.label.bs_class }} mx-1">{{ label.label.name }}</span>
                    {% empty %}
                        {% translate "No label" %}
                    {% endfor %}
                    <div class="d-flex justify-content-center mt-4">
                        <a href="{% url "hrcentre:user_labels" main.character.character_ownership.user.id %}" class="btn btn-info"><i class="fa-solid fa-pencil"></i></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row mt-4">
        <div class="col-12 px-4">
            <div class="card text-center">
                {% with notes=main.character.character_ownership.user.hr_notes %}
                    <div class="card-header">{% translate "Notes" %}</div>
                    <div class="card-body">
                        {% if notes.notes %}
                            <p class="card-text">{{ notes.notes }}</p>
                        {% else %}
                            <p class="card-text fst-italic">{% translate "Empty notes" %}</p>
                        {% endif %}
                        <div class="d-flex justify-content-center mt-4">
                            <a href="{% url "hrcentre:user_notes" main.character.character_ownership.user.id %}" class="btn btn-info"><i class="fa-solid fa-pencil"></i></a>
                        </div>
                    </div>
                    <div class="card-footer text-body-secondary">
                        <div class="d-flex justify-content-between">
                            <span>
                                {% blocktranslate with created_by=notes.added_by.profile.main_character|default:"-" created_at=notes.added_on|date:"Y/m/d H:i e"|default:"-" %}
                                    Created by: {{ created_by }} ({{ created_at }})
                                {% endblocktranslate %}
                            </span>
                            <span>
                                {% blocktranslate with updated_by=notes.last_updated_by.profile.main_character|default:"-" updated_at=notes.last_updated_on|date:"Y/m/d H:i e"|default:"-" %}
                                    Updated by: {{ updated_by }} ({{ updated_at }})
                                {% endblocktranslate %}
                            </span>
                        </div>
                    </div>
                {% endwith %}
            </div>
        </div>
    </div>
{% endblock hrcentre_content %}